const all_languages = [
  {
     "tag":"Afrikaans",
     "code":"af",
     "name":"Afrikaans"
  },
  {
     "tag":"Albanian",
     "code":"sq",
     "name":"Shqip"
  },
  {
     "tag":"Amharic",
     "code":"am",
     "name":"አማርኛ"
  },
  {
     "tag":"Arabic",
     "code":"ar",
     "name":"العربية"
  },
  {
     "tag":"Armenian",
     "code":"hy",
     "name":"Հայերեն"
  },
  {
     "tag":"Azeerbaijani",
     "code":"az",
     "name":"azərbaycan dili"
  },
  {
     "tag":"Basque",
     "code":"eu",
     "name":"euskara"
  },
  {
     "tag":"Belarusian",
     "code":"be",
     "name":"беларуская мова"
  },
  {
     "tag":"Bengali",
     "code":"bn",
     "name":"বাংলা"
  },
  {
     "tag":"Bosnian",
     "code":"bs",
     "name":"bosanski jezik"
  },
  {
     "tag":"Bulgarian",
     "code":"bg",
     "name":"български език"
  },
  {
     "tag":"Catalan",
     "code":"ca",
     "name":"català"
  },
  {
     "tag":"Cebuano",
     "code":"ceb",
     "name":"Cebuano"
  },
  {
    "tag":"Traditional Chinese",
    "code":"zh_Hant",
    "name":"繁體中文"
  },
  {
     "tag":"Simplified Chinese",
     "code":"zh_Hans",
     "name":"简体中文"
  },
  {
     "tag":"Corsican",
     "code":"co",
     "name":"corsu"
  },
  {
     "tag":"Croatian",
     "code":"hr",
     "name":"hrvatski jezik"
  },
  {
     "tag":"Czech",
     "code":"cs",
     "name":"čeština"
  },
  {
     "tag":"Danish",
     "code":"da",
     "name":"dansk"
  },
  {
     "tag":"Dutch",
     "code":"nl",
     "name":"Nederlands"
  },
  {
     "tag":"English",
     "code":"en",
     "name":"English"
  },
  {
     "tag":"Esperanto",
     "code":"eo",
     "name":"Esperanto"
  },
  {
     "tag":"Estonian",
     "code":"et",
     "name":"eesti"
  },
  {
     "tag":"Finnish",
     "code":"fi",
     "name":"suomi"
  },
  {
     "tag":"French",
     "code":"fr",
     "name":"français"
  },
  {
     "tag":"Frisian",
     "code":"fy",
     "name":"Frysk"
  },
  {
     "tag":"Galician",
     "code":"gl",
     "name":"Galego"
  },
  {
     "tag":"Georgian",
     "code":"ka",
     "name":"ქართული"
  },
  {
     "tag":"German",
     "code":"de",
     "name":"Deutsch"
  },
  {
     "tag":"Greek",
     "code":"el",
     "name":"ελληνικά"
  },
  {
     "tag":"Gujarati",
     "code":"gu",
     "name":"ગુજરાતી"
  },
  {
     "tag":"Haitian Creole",
     "code":"ht",
     "name":"Kreyòl ayisyen"
  },
  {
     "tag":"Hausa",
     "code":"ha",
     "name":"هَوُسَ"
  },
  {
     "tag":"Hawaiian",
     "code":"haw",
     "name":"ʻŌlelo Hawaiʻi"
  },
  {
     "tag":"Hebrew",
     "code":"iw",
     "name":"עברית"
  },
  {
     "tag":"Hindi",
     "code":"hi",
     "name":"हिन्दी, हिंदी"
  },
  {
     "tag":"Hmong",
     "code":"hmn",
     "name":"Hmoob"
  },
  {
     "tag":"Hungarian",
     "code":"hu",
     "name":"magyar"
  },
  {
     "tag":"Icelandic",
     "code":"is",
     "name":"Íslenska"
  },
  {
     "tag":"Igbo",
     "code":"ig",
     "name":"Asụsụ Igbo"
  },
  {
     "tag":"Indonesian",
     "code":"id",
     "name":"Bahasa Indonesia"
  },
  {
     "tag":"Irish",
     "code":"ga",
     "name":"Gaeilge"
  },
  {
     "tag":"Italian",
     "code":"it",
     "name":"Italiano"
  },
  {
     "tag":"Japanese",
     "code":"ja",
     "name":"日本語"
  },
  {
     "tag":"Javanese",
     "code":"jw",
     "name":"Basa Jawa"
  },
  {
     "tag":"Kannada",
     "code":"kn",
     "name":"ಕನ್ನಡ"
  },
  {
     "tag":"Kazakh",
     "code":"kk",
     "name":"қазақ тілі"
  },
  {
     "tag":"Khmer",
     "code":"km",
     "name":"ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ"
  },
  {
     "tag":"Korean",
     "code":"ko",
     "name":"한국어"
  },
  {
     "tag":"Kurdish",
     "code":"ku",
     "name":"Kurdî"
  },
  {
     "tag":"Kyrgyz",
     "code":"ky",
     "name":"Кыргызча"
  },
  {
     "tag":"Lao",
     "code":"lo",
     "name":"ພາສາລາວ"
  },
  {
     "tag":"Latin",
     "code":"la",
     "name":"latine"
  },
  {
     "tag":"Latvian",
     "code":"lv",
     "name":"Latviešu"
  },
  {
     "tag":"Lithuanian",
     "code":"lt",
     "name":"lietuvių kalba"
  },
  {
     "tag":"Luxembourgish",
     "code":"lb",
     "name":"Lëtzebuergesch"
  },
  {
     "tag":"Macedonian",
     "code":"mk",
     "name":"македонски јазик"
  },
  {
     "tag":"Malagasy",
     "code":"mg",
     "name":"fiteny malagasy"
  },
  {
     "tag":"Malay",
     "code":"ms",
     "name":"بهاس ملايو"
  },
  {
     "tag":"Malayalam",
     "code":"ml",
     "name":"മലയാളം"
  },
  {
     "tag":"Maltese",
     "code":"mt",
     "name":"Malti"
  },
  {
     "tag":"Maori",
     "code":"mi",
     "name":"te reo Māori"
  },
  {
     "tag":"Marathi",
     "code":"mr",
     "name":"मराठी"
  },
  {
     "tag":"Mongolian",
     "code":"mn",
     "name":"Монгол хэл"
  },
  {
     "tag":"Myanmar",
     "code":"my",
     "name":"ဗမာစာ"
  },
  {
     "tag":"Nepali",
     "code":"ne",
     "name":"नेपाली"
  },
  {
     "tag":"Norwegian",
     "code":"no",
     "name":"Norsk"
  },
  {
     "tag":"Nyanja",
     "code":"ny",
     "name":"chinyanja"
  },
  {
     "tag":"Pashto",
     "code":"ps",
     "name":"پښتو"
  },
  {
     "tag":"Persian",
     "code":"fa",
     "name":"فارسی"
  },
  {
     "tag":"Polish",
     "code":"pl",
     "name":"język polski"
  },
  {
     "tag":"Portuguese",
     "code":"pt",
     "name":"Português"
  },
  {
     "tag":"Punjabi",
     "code":"pa",
     "name":"ਪੰਜਾਬੀ"
  },
  {
     "tag":"Romanian",
     "code":"ro",
     "name":"Română"
  },
  {
     "tag":"Russian",
     "code":"ru",
     "name":"Русский"
  },
  {
     "tag":"Samoan",
     "code":"sm",
     "name":"gagana fa'a Samoa"
  },
  {
     "tag":"Scots Gaelic",
     "code":"gd",
     "name":"Gàidhlig"
  },
  {
     "tag":"Serbian",
     "code":"sr",
     "name":"српски језик"
  },
  {
     "tag":"Sesotho",
     "code":"st",
     "name":"Sesotho"
  },
  {
     "tag":"Shona",
     "code":"sn",
     "name":"chiShona"
  },
  {
     "tag":"Sindhi",
     "code":"sd",
     "name":"सिन्धी"
  },
  {
     "tag":"Sinhala",
     "code":"si",
     "name":"සිංහල"
  },
  {
     "tag":"Slovak",
     "code":"sk",
     "name":"Slovenčina"
  },
  {
     "tag":"Slovenian",
     "code":"sl",
     "name":"Slovenski Jezik"
  },
  {
     "tag":"Somali",
     "code":"so",
     "name":"Soomaaliga"
  },
  {
     "tag":"Spanish",
     "code":"es",
     "name":"Español"
  },
  {
     "tag":"Sundanese",
     "code":"su",
     "name":"Basa Sunda"
  },
  {
     "tag":"Swahili",
     "code":"sw",
     "name":"Kiswahili"
  },
  {
     "tag":"Swedish",
     "code":"sv",
     "name":"Svenska"
  },
  {
     "tag":"Tagalog",
     "code":"tl",
     "name":"Wikang Tagalog"
  },
  {
     "tag":"Tajik",
     "code":"tg",
     "name":"тоҷикӣ"
  },
  {
     "tag":"Tamil",
     "code":"ta",
     "name":"தமிழ்"
  },
  {
     "tag":"Telugu",
     "code":"te",
     "name":"తెలుగు"
  },
  {
     "tag":"Thai",
     "code":"th",
     "name":"ไทย"
  },
  {
     "tag":"Turkish",
     "code":"tr",
     "name":"Türkçe"
  },
  {
     "tag":"Ukrainian",
     "code":"uk",
     "name":"Українська"
  },
  {
     "tag":"Urdu",
     "code":"ur",
     "name":"اردو"
  },
  {
     "tag":"Uzbek",
     "code":"uz",
     "name":"Ўзбек"
  },
  {
     "tag":"Vietnamese",
     "code":"vi",
     "name":"Tiếng Việt"
  },
  {
     "tag":"Welsh",
     "code":"cy",
     "name":"Cymraeg"
  },
  {
     "tag":"Xhosa",
     "code":"xh",
     "name":"isiXhosa"
  },
  {
     "tag":"Yiddish",
     "code":"yi",
     "name":"ייִדיש"
  },
  {
     "tag":"Yoruba",
     "code":"yo",
     "name":"Yorùbá"
  },
  {
     "tag":"Zulu",
     "code":"zu",
     "name":"isiZulu"
  }
]

export default all_languages