const constants = {
  AppName: 'SCRIBBBBLE',
  Login: 'Login',
  Register: 'Register',
  Signup: 'Signup',
  Logout: 'Logout',
  Username: 'Username',
  Password: 'Password',
  Email: 'Email',
  ForgotPassword: 'Forgot password?',
  AlreadyHaveAcc: 'Already have an account? Login',
  DoNotHaveAcc: "Don't have an account? Register",
  UploadImage: 'Upload image',
  AdminConsole: 'Admin Console',
  Analyse: 'Analyse',
  Endpoint: 'Endpoint',
  RequestPswdReset: 'Request Password Reset',
  ResetPassword: 'Reset Password',
  User: 'User',
  Method: 'Method',
  Endpoint: 'Endpoint',
  NumRequests: 'Number of Requests',
  TotalNumRequests: 'Total Number of Requests',
  msg: {
    UsernameVal: 'You must enter a valid username',
    PasswordVal: 'You must enter a password',
    PasswordMinVal: 'Password must be at least 8 characters',
    RegisterSuccess: 'Account created successfully',
    RegisterFail: 'Registration failed',
    LoginFail: 'Login failed',
    ResetPswdReqSuccess: 'A password reset link has been sent to {0}',
    ResetPswdReqFail: 'Failed to send reset password request',
    ResetPswdSuccess: 'Password reset successfully',
    ResetPswdFail: 'Failed to reset password',
  },
  action: {
    Close: 'CLOSE',
  }
}

export default constants